name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Ruby Dependencies
      working-directory: ./payslip-generator
      run: |
        gem install bundler
        bundle install
    - name: Run Minitest
      working-directory: ./payslip-generator
      run: |
        ruby payslip_test.rb
